### ISSUE TITLE
EOSAuth.LoginCallbackInfo never called

### ISSUE THREAD

**Issue by dkoding** [Bearwaves/eos4j#3]
I do this:

```
  EOS.loadLibraries() // Works
  EOS.initialize(new EOS.InitializeOptions(title, version)); // Works

  EOSPlatform eosPlatform = new EOSPlatform(new EOSPlatform.Options(
                    System.getProperty("EPIC_PRODUCT_ID"),
                    System.getProperty("EPIC_SANDBOX_ID"),
                    System.getProperty("EPIC_DEPLOYMENT_ID"),
                    System.getProperty("EPIC_CLIENT_ID"),
                    System.getProperty("EPIC_CLIENT_SECRET"),
                    EOSPlatform.Flag.WINDOWS_ENABLE_OVERLAY_OPENGL.getValue()
            )); // Works, handle retrieved

    new Thread(() -> eosPlatform.tick()).start();

   eosPlatform.getAuthHandle().login(new EOSAuth.LoginOptions(
                authToken == null ?
                        new EOSAuth.Credentials(EOS.LoginCredentialType.EXCHANGE_CODE, null, exchangeCode) :
                        new EOSAuth.Credentials(EOS.LoginCredentialType.REFRESH_TOKEN, null, authToken.getRefreshToken()),
                0
        ), data -> {
            try {
                EOS.throwIfErrorCode(data.resultCode);  // This does NOT work, never called
            } catch (EOSException e) {
                Gdx.app.error("EpicPlatformManager", "Auth login failed", e);
                return;
            }
        }
```

The exchangecode = the value from -AUTH_PASSWORD from the Epic Games Launcher.
It does not matter if I run this locally or via the Epic Store Launcher.
If I use EOSAuth.Credentials(EOS.LoginCredentialType.DEVELOPER, "localhost:1245", "RSV") the DevAuthTool server is never called either, there is no network traffic at all.

SDK / DLL version is 1.16.1. I have also tried with 1.15.5 with the same result.

**Comment by JoelOtter** [comment]
I might be being stupid / bad at modern Java here but does this

```java
new Thread(() -> eosPlatform.tick()).start();
```
result in your tick being called only once? You want to call that on every frame, otherwise the callbacks within the EOS SDK itself (not eos4j!) will never be called.

If you _are_ calling it on every frame already, you may be running into something like [an issue I had](https://eoshelp.epicgames.com/s/question/0D54z00008wLjJSCA0/eosplatformcreate-segmentation-fault-on-linux-and-macos?language=en_US) where there are some weird conditions on which that needs to be called. On macOS it needs to be called inside a CFRunLoop - I believe you're on Windows, not sure if you need something like that. Are you using a framework like LWJGL to handle your windowing? It ought to work within the render loop there.

**Comment by dkoding** [comment]
Your 'modern Java' understanding is correct, I stupidly assumed this would run the thread in the background (natively) - which in retrospect of course is not the case. 

Modifying my code to run this at 10 fps certainly fixed the problem!

Thanks for creating this project and for teaching me how to program Java. :-)

**Comment by JoelOtter** [comment]
Great, glad to know it's working! And thank you for stress-testing the library, I believe you're the first. :) Excited to see what you do with it.
